#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"

DOTBOT_BIN="/opt/homebrew/bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"

"${BASEDIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
