
set allow-duplicate-recipes
set positional-arguments
set dotenv-load
set export


# Colors
RED    := "\\u001b[31m"
GREEN  := "\\u001b[32m"
YELLOW := "\\u001b[33m"
BOLD   := "\\u001b[1m"
RESET  := "\\u001b[0m"

# List available recipes
default:
    just --list --unsorted
    
# List available recipes
help:
    @just --list --unsorted
    

# Will notify an SRE with a boring mail.
notify:
    @just _bold_squares "{{YELLOW}}WARNING"    


_bold_squares message:
	@echo -e "{{BOLD}}[{{RESET}}{{message}}{{RESET}}{{BOLD}}]{{RESET}}"    
    
